Написал функцию, которая суммирует два числа
js-tasks-ru/jsbasic-20211014_max168 pull request #1
Opened 2021-10-18 11:38 UTC by Maxim20l

2021-10-18 11:38 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @stas-dolgachov должен запустить тесты.

2021-10-18 16:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-18 16:32 UTC, dolgachio requested changes

2021-10-18 16:32 UTC, stas-dolgachov commented on 0-module/1-task/index.js
> +function sum(a, b){
У вас здесь объявлено 2 функции с одинаковыми именами. Такой код будет выдавать ошибку. Удалите, пожалуйста, одну из них

2021-10-20 07:13 UTC, jsru commented
Добавляю преподавателя (@stas-dolgachov) для код-ревью.

2021-10-20 07:16 UTC, stas-dolgachov approved these changes

2021-10-20 07:16 UTC, stas-dolgachov commented on 0-module/1-task/index.js
> +  return a + b;
👍

2021-10-20 07:16 UTC, merged